services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8874942259:AAFr1tjVSHMGIRKZT9ZV7oJ2gsAfdi0vIVs"